version: '3'
services:
  mysql-container:
    image: mysql
    container_name: mysql-container
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql

  phpmyadmin-container:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - '8080:80'
    links:
      - mysql-container:db
